### ISSUE TITLE
Remove `zio-json` dependency

### ISSUE THREAD

**Issue by KacperFKorban** [lumidion/sbt-sonatype-central#8]
Hi, thanks for creating this plugin.

As per the comment in `sbt-ci-realese`, adding a `zio-json` as a dependency adds some controversy.
Would it be possible to use e.g. [`sjon-new`](https://index.scala-lang.org/eed3si9n/sjson-new), since it is already the go to json library in `sbt`?

Original comment (https://github.com/sbt/sbt-ci-release/pull/298#pullrequestreview-2169049028):
> Does this transitively introduce Zio dependency just for JSON decoding? Could we use Contraband / sjson-new that are already in use for sbt or uPickle instead?

**Comment by Andrapyre** [comment]
@KacperFKorban, closing this now that https://github.com/lumidion/sonatype-central-client/pull/6 and https://github.com/lumidion/sbt-sonatype-central/pull/10 are merged with fresh releases.

**Comment by KacperFKorban** [comment]
Thanks! :heart:
